<!DOCTYPE html>

<html lang="en">

<head>
    <title>Pileshkiq About</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="../css/about.css" />
</head>

<body>
    <?php 
        include_once '../php/header.php';
    ?>

    <main>
        <div>
            <h1>About us</h1>
            <p>
                Welcome to our chicken-themed website! We're passionate about all
                things chicken and excited to share our knowledge with you. Whether
                you're a backyard chicken enthusiast or simply curious about these
                amazing birds, our website has something for everyone. Our journey
                started with a love for the fascinating world of chickens. We wanted
                to create a resource that would help others discover the many
                interesting and unique aspects of these birds. That's why we created
                this website – to share our knowledge and passion with others. Our
                mission is to provide helpful information about chickens and promote
                their benefits. We believe that chickens are fascinating and valuable
                animals that can be enjoyed in a variety of ways. From backyard flocks
                to commercial farms, chickens play an important role in our world.
            </p>
        </div>

        <h1 class="our-team">Our Team</h1>
        <div class="cards">
            <div class="container">
                <img src="../pictures/1jolynePNG.webp" />
                <div>
                    <h2>Pileshkiq</h2>
                    <p class="title">CEO & Founder</p>
                    <p>Genius, Billionaire, Playboy, Philanthropist</p>
                    <p class="small">vgan3v@gmail.com</p>
                </div>
            </div>

            <div class="container">
                <img src="../pictures/1hentie.webp" />
                <div>
                    <h2>Midjourney</h2>
                    <p class="title">Art Director</p>
                    <p>Best artist ever (the art is generated by AI)</p>
                    <p class="small">MidjourneyAI@gmail.com</p>
                </div>
            </div>

            <div class="container">
                <img src="../pictures/1shanks.webp" />
                <div>
                    <h2>Pileshkiq</h2>
                    <p class="title">Designer</p>
                    <p>Greatest designer in history (the design is stolen)</p>
                    <p class="small">vgan3v@gmail.com</p>
                </div>
            </div>
        </div>
    </main>

    <footer>
        <p>&copy;2023 Pileshkiq</p>
    </footer>
</body>

</html>