<!DOCTYPE html>
<html lang="en">

<head>
    <title>Pileshkiq About</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/style.css">
</head>

<body class="about-body">
    <?php
    include_once 'header.php';
    ?>

    <section class="about-section">
        <div class="about-content">
            <img src="../pictures/AIpile4.webp" alt="">
            <div class="about-text">
                <h1>About Us</h1>
                <h5>Chicks <span>& eggs</span></h5>
                <p>
                    Welcome to our chicken-themed website! We're passionate about all
                    things chicken and excited to share our knowledge with you. Whether
                    you're a backyard chicken enthusiast or simply curious about these
                    amazing birds, our website has something for everyone. Our journey
                    started with a love for the fascinating world of chickens. We wanted
                    to create a resource that would help others discover the many
                    interesting and unique aspects of these birds. The website was
                    made by the amazing team below
                </p>
            </div>
        </div>
    </section>

    <div class="about-container">
        <a href="https://github.com/P1l3T0" target="_blank">
            <div class="about-cards fly-in">
                <img src="../pictures/1jolynePNG.webp" />
                <h2>Pileshkiq</h2>
                <h5 class="title">CEO & Founder</h5>
                <p class="small">Genius, Billionaire, Playboy, Philanthropist</p>
                <p class="email">vgan3v@gmail.com</p>
            </div>
        </a>

        <a href="https://www.midjourney.com/home/" target="_blank">
            <div class="about-cards fly-in">
                <img src="../pictures/1hentie.webp" />
                <h2>Midjourney</h2>
                <h5 class="title">Art Director</h5>
                <p class="small">Artist #1 (the art is generated by AI)</p>
                <p class="email">MidjourneyAI@gmail.com</p>
            </div>
        </a>

        <a href="https://www.linkedin.com/in/vasil-ganev-2507a3210/" target="_blank">
            <div class="about-cards fly-in">
                <img src="../pictures/1shanks.webp" />
                <h2>Pileshkiq again</h2>
                <h5 class="title">Designer</h5>
                <p class="small">S-tier designer (the design is stolen)</p>
                <p class="email">vgan3v@gmail.com</p>
            </div>
        </a>
    </div>

    <?php
    include_once 'footer.html';
    ?>
</body>

</html>